# Generated by Django 2.2.14 on 2021-01-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='群組名')),
            ],
            options={
                'verbose_name': '推播群組',
                'verbose_name_plural': '推播群組',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='推播內容')),
                ('stopID', models.IntegerField(verbose_name='目前發送至此')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='發送日期')),
            ],
            options={
                'verbose_name': '歷史紀錄',
                'verbose_name_plural': '歷史紀錄',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('username', models.CharField(default='unknow', max_length=2048, verbose_name='用戶名')),
                ('userType', models.CharField(default='unknow', max_length=20, verbose_name='種類')),
                ('groups', models.ManyToManyField(to='api.BroadcastGroup', verbose_name='群組')),
            ],
            options={
                'verbose_name': '推播用戶',
                'verbose_name_plural': '推播用戶',
            },
        ),
    ]
