# Generated by Django 2.2.14 on 2021-01-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='groups',
            field=models.ManyToManyField(blank=True, to='api.BroadcastGroup', verbose_name='群組'),
        ),
    ]
